package me.chriss99.lib

enum class Card(val color: Color, val number: Int) {
    R1(Color.RED, 1),
    R2(Color.RED, 2),
    R3(Color.RED, 3),
    R4(Color.RED, 4),
    R5(Color.RED, 5),
    R6(Color.RED, 6),
    R7(Color.RED, 7),
    R8(Color.RED, 8),
    R9(Color.RED, 9),
    RA(Color.RED, 10),
    RB(Color.RED, 11),
    RC(Color.RED, 12),
    RD(Color.RED, 13),
    RE(Color.RED, 14),
    G1(Color.GREEN, 1),
    G2(Color.GREEN, 2),
    G3(Color.GREEN, 3),
    G4(Color.GREEN, 4),
    G5(Color.GREEN, 5),
    G6(Color.GREEN, 6),
    G7(Color.GREEN, 7),
    G8(Color.GREEN, 8),
    G9(Color.GREEN, 9),
    GA(Color.GREEN, 10),
    GB(Color.GREEN, 11),
    GC(Color.GREEN, 12),
    GD(Color.GREEN, 13),
    GE(Color.GREEN, 14),
    B1(Color.BLUE, 1),
    B2(Color.BLUE, 2),
    B3(Color.BLUE, 3),
    B4(Color.BLUE, 4),
    B5(Color.BLUE, 5),
    B6(Color.BLUE, 6),
    B7(Color.BLUE, 7),
    B8(Color.BLUE, 8),
    B9(Color.BLUE, 9),
    BA(Color.BLUE, 10),
    BB(Color.BLUE, 11),
    BC(Color.BLUE, 12),
    BD(Color.BLUE, 13),
    BE(Color.BLUE, 14),
    Y1(Color.YELLOW, 1),
    Y2(Color.YELLOW, 2),
    Y3(Color.YELLOW, 3),
    Y4(Color.YELLOW, 4),
    Y5(Color.YELLOW, 5),
    Y6(Color.YELLOW, 6),
    Y7(Color.YELLOW, 7),
    Y8(Color.YELLOW, 8),
    Y9(Color.YELLOW, 9),
    YA(Color.YELLOW, 10),
    YB(Color.YELLOW, 11),
    YC(Color.YELLOW, 12),
    YD(Color.YELLOW, 13),
    YE(Color.YELLOW, 14),
    F1(Color.FOOL, 0),
    F2(Color.FOOL, 0),
    F3(Color.FOOL, 0),
    F4(Color.FOOL, 0);

    val indexBit: Long = 1L shl ordinal

    enum class Color {
        RED,
        GREEN,
        BLUE,
        YELLOW,
        FOOL
    }
}